# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release channel'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
          - prev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - run: bun publish --tag ${{ inputs.tag }}
        working-directory: ./packages/merge-sx
        env:
          NPM_KEY: ${{secrets.NPM_KEY}}
