name: Patch

on: workflow_dispatch

permissions:
  contents: write

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: fregante/setup-git-user@v2
      - run: pnpm -C packages/merge-sx version patch
      - run: git push && git push --tags
